steps:
  - simple_align:
      cases: always
      top_level_patterns: always
      records: always
      multi_way_if: always

  - imports:
      align: none
      list_align: after_alias
      pad_module_names: true
      long_list_align: multiline
      empty_list_align: inherit
      list_padding: 2
      separate_lists: true
      space_surround: false
      post_qualify: false
      group_imports: false
      group_rules:
        - match: ".*"
          sub_group: "^[^.]+"

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
      language_prefix: LANGUAGE

  - trailing_whitespace: {}

columns: 80
newline: lf
cabal: false
