module Asm.Types.Pass4 (Pass4Artifacts) where

import Data.Word (Word8)

import Asm.Types.Pass3 (Pass3Artifacts)


-- | Assembler artifacts generated by the end of pass4, if successful
type Pass4Artifacts =
  ( [Word8]         -- output bytes
  , Pass3Artifacts  -- kept for posterity
  )
