module Asm.Types.Pass3 (Pass3Artifacts) where

import Data.Word (Word8)

import Asm.Types.Pass2 (Pass2Artifacts)


-- | Assembler artifacts generated by the end of pass3, if successful
type Pass3Artifacts =
  ( [Word8]         -- output bytes
  , Pass2Artifacts  -- kept for posterity
  )
